@startuml
left to right direction
actor Usuario as Usuario
package Quest{
    package Menu{
        usecase "Jugar" as Jugar
        usecase "Consultar Controles" as Controles
        usecase "Salir" as Salir
    }
    package Jugando{
        actor Pirata as Pirata
        package Ronda{
            usecase "Mover Pirata" as MoverPirata
            usecase "Desenterrar" as Desenterrar
            usecase "Agarrar Potenciador" as AgarrarPotenciador
            usecase "Perder Vida" as PerderVida
            usecase "Pasar ronda" as PasarRonda
            usecase "Saber distancia a objeto más cercano" as SaberDistancia
            
            usecase "Desenterrar trampa" as DTrampa
            usecase "Desenterrar tesoro" as DTesoro
            usecase "Desenterrar Nada" as DNada
            usecase "Desenterrar Potenciador" as DPotenciador

        }
        usecase "Controlar Pirata" as Controlar
        usecase "Ver interfaz" as VInterfaz
        package Interfaz{
            package Puntuación{
                usecase "Ver Puntuación" as VPuntuacion
                usecase "Modificar Puntuación" as MPuntuacion
                }
            usecase "Ver Brújula" as VBrujula 
            usecase "Ver Corazones" as VCorazon
        }
        package Game_over{
            usecase "Volver al Menu" as VolverMenu
            usecase "Retry" as Retry

        }
    }
}
Usuario -- Jugar
Usuario -- Controles
Usuario -- Salir
Jugar <|-- Controlar
Jugar <|-- VInterfaz
Desenterrar <|-- DTrampa
Desenterrar <|-- DTesoro
Desenterrar <|-- DNada
Desenterrar <|-- DPotenciador
DTrampa -- PerderVida
DTesoro -- PasarRonda
DPotenciador -- AgarrarPotenciador
Controlar <|-- Pirata
Pirata -- MoverPirata
Pirata -- Desenterrar
MPuntuacion <-- AgarrarPotenciador
MPuntuacion <-- PerderVida
MPuntuacion <-- PasarRonda
Pirata -- SaberDistancia
VCorazon -- Pirata
VInterfaz <|-- VCorazon
VInterfaz <|-- VBrujula
VInterfaz <|-- VPuntuacion
VBrujula <|-- SaberDistancia
Menu <-- VolverMenu
Jugar <-- Retry
@enduml
